### ISSUE TITLE
Prefer alternating scores to scrolling

### ISSUE THREAD

**Issue by timparenti** [AcmeTensorToys/esp-lua_ctfws#5]
Without resorting to scrolling, the second line of the displays can support when the number of flags (`nflags`) and the team scores (`flags.red`, `flags.yel`) collectively contain 12 or fewer characters/digits — the other 8 characters being used to format the output:

```
0         1
01234567890123456789
NN⚑: R=NNNNN Y=NNNNN
```

**Recommendation:** Rather than resorting to scrolling when the scoring line becomes too long, the display should instead alternate between displaying the `flags.red` and `flags.yel` scores alongside the `nflags` count, perhaps displaying each for ~2 seconds:

```
0         1
01234567890123456789
   NN⚑: R=NNNNNNN
   NN⚑: Y=NNNNNNN
```

Bonus points if, while the messages stay centered normally, the score which takes fewer characters is padded so that direct comparisons can be made as the scores alternate:

```
0         1
01234567890123456789
   NN⚑: R=NNNNNNN
   NN⚑: Y=  NNNNN
```

In the unlikely event that either score, when combined with the `nflags` count, requires 16 or more characters (i.e., even one score wouldn't fit), then perhaps we would resort to scrolling. I suppose, even if these are 32-bit integers, this could be possible with millions of flags. ;)

**Comment by nwf** [comment]
This should be working; please re-open if not.
