### ISSUE TITLE
Lower MQTT keepalive period

### ISSUE THREAD

**Issue by nwf** [AcmeTensorToys/esp-lua_ctfws#7]
The keepalive should be set to ~2.5x the hearbeat period or something like that.  Something much smaller than the 1500 seconds it currently is by default.  This can be changed in the `nwfmqtt.conf` files on the devices, but that requires someone knowing how to use `luatool` and friends.  This is to remind me to make the change before shipping the next firmware, I guess. :)

**Comment by timparenti** [comment]
@nwf Relatedly (insofar as it might affect your fix here), it was expressed that the device heartbeats themselves were a bit too infrequent.  This was a remark based on the web interface, but I suspect that's updating about as promptly as beats are received.

If the beat interval is currently 60 seconds, perhaps something like 20 would be better.

**Comment by nwf** [comment]
Resolved as part of today's push.
